### PR TITLE
Reduce memory limit

### PR DESCRIPTION
**Pull request by core23**
Reduces memory limit for large projects

Refs: https://github.com/sonata-project/SonataAdminBundle/pull/5766/checks?check_run_id=325006757

### CODE REVIEW

**Comment by core23** [comment]
ping @OskarStark

**Review by OskarStark — APPROVED** [review]

**Comment by adaamz** [comment]
reduce? i would say extend to "unlimited"

**Comment by OskarStark** [comment]
Yes it was a but misleading.
Let’s see if it is working or just limited by the GA environment

**Comment by core23** [comment]
It's working on our admin bundle

**Pull request merged**
