### PR TITLE
Show version of PHPStan

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]
This definitely makes sense to me, what about adding a second line, using composer show | grep phpstan to show the installed  extension versions ?

**Comment by Nyholm** [comment]
Yeah. I think that makes sense. 
I’ll make the update when I’m at a computer.

**Comment by OskarStark** [comment]
Thanks, I am currently on a phone too

**Comment by OskarStark** [comment]
Thank you @Nyholm I will show the used version in a separate PR

**Comment by Nyholm** [comment]
Thank you for merging

**Pull request merged**
