### PR TITLE
Use composer show's wildcard feature

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by OskarStark** [comment]
Hi 👋 

Can you explain whats wrong with the initial version using `grep`?

**Comment by szepeviktor** [comment]
> Can you explain whats wrong with the initial version using `grep`?

There is nothing wrong with grep, just Composer can do this alone.

**Comment by szepeviktor** [comment]
This is an improvement, not a fix.

**Comment by OskarStark** [comment]
Thank you 👍

**Pull request merged**
