### PR TITLE
Add support for pre/post composer commands

### LINKED ISSUE #66: allow more composer options?
In a project of mine, I need to allow minimum stability "dev" in composer, to be ready when my vendor will release a stable version.
This is not possible, or I may be missing something.

If not possible yet, it would be nice to have the possibility to run the following

 composer config minimum-stability dev
 composer config prefer-stable true

### PR DESCRIPTION
**Pull request by garak**
Fix #66

### CODE REVIEW

**Comment by OskarStark** [comment]
Er already have REQUIRE_DEV, can't we use this?

**Comment by garak** [comment]
But it's not meant for the same purpose

**Comment by OskarStark** [comment]
I agree, will merge and release tomorrow

**Comment by OskarStark** [comment]
On a second thought, what about adding an option for pre and post commands as array? So everyone can execute what he wants? Does this makes sense?

**Comment by garak** [comment]
You're right, it could be more flexible indeed.
I'll try to propose something

**Comment by garak** [comment]
I changed my PR accordingly, but I'm not 100% confident if I did it the right way (sorry, I'm not very skilled in bash)
Let me know

**Comment by OskarStark** [comment]
> sorry, I'm not very skilled in bash

Me neither 😄 

Lets see if it works :-)

**Comment by OskarStark** [comment]
I released 1.10

**Comment by dbu** [comment]
this breaks the build with a [bash error](https://github.com/phpcr/phpcr-utils/actions/runs/7006048713/job/19057072580) about "bad substitution": 

i had to downgrade to 1.8.0 to get my build to work again. 1.9.0 seems [not installable with docker](https://github.com/phpcr/phpcr-utils/actions/runs/7006228920/job/19057642773), dunno why.

**Comment by OskarStark** [comment]
Weird as this was released in 1.10

**Comment by dbu** [comment]
i was using latest, so it installed 1.10.0 which has this change and failed.

**Comment by OskarStark** [comment]
@garak does it work for you if you provide your commands?

**Comment by dbu** [comment]
note that i do not provide any commands. 

i guess it is supposed to work in that case too, but maybe something is wrong. not sure if maybe there is some name clash in github actions when one does not explicitly define the variables.

**Comment by OskarStark** [comment]
> note that i do not provide any commands.

Yes, that's why I wanted to know if it works with commands as expected, in this case we must provide a default when someone tries to run the action without commands

**Comment by OskarStark** [comment]
Lets revert this for now

**Pull request merged**
